# A push on master will build, test and publish Jeka on OSSRH.
# Beside it will push the built documentation on the Jeka landing page.

# If a tag is present on the last commit, Jeka will publish versioned artifacts according tag name on OSSRH public repo.
# If no tag is present, the built artifacts will be published to OSSRH snapshot repository.
# This logic is implemented within the Jeka build.

name: Java Build and Publish

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: git fetch --prune --unshallow --tags
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build and publish
      env:
        OSSRH_USER: ${{ secrets.OSSRH_USER }}
        OSSRH_PWD: ${{ secrets.OSSRH_PWD }}
        JEKA_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: ./jeka self#buildJar maven#publish build#publishOnMavenCentral=true